version: '2'
services:
    pruebajhonline-app:
        image: pruebajhonline
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://pruebajhonline-mssql:1433;database=pruebaJHOnline
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pruebajhonline-mssql:
        extends:
            file: mssql.yml
            service: pruebajhonline-mssql
